### ISSUE TITLE
🐞 Bug: The docker container freezes trying to ensure ownership of /app

### ISSUE THREAD

**Issue by driftywinds** [ofkm/arcane#109]
### Bug Description

```
arcane  | Entrypoint: Running as root. Setting up user and permissions...
arcane  | Entrypoint: Using PUID=1000, PGID=1000, DOCKER_GID=991
arcane  | Entrypoint: Group with GID 1000 already exists: arcane
arcane  | Entrypoint: Updating docker group from GID 998 to 991...
arcane  | Entrypoint: User with UID 1000 already exists: arcane
arcane  | Docker socket accessible at /var/run/docker.sock (GID: 991)
arcane  | Entrypoint: Ensuring ownership of /app for 1000:1000...

```
it just shows me this and stays there for eternity

### Steps To Reproduce

copy paste the compose file and ```docker compose up -d```

### Expected Behavior

It should start up normally

### Actual Behavior

It gets stuck and never goes past

### Arcane Version

latest

### Operating System

Linux

### Browser

n.a

### Docker Version

latest

**Comment by kmendell** [comment]
What does your compose file look like? This is odd, I will have to do some testing once i see what it looks like. I run mine with user: root, but i tested rootless as well and it worked but i could have missed something.

**Comment by driftywinds** [comment]
here is my compose file - 
```
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3028:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./arcane-data:/app/data
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_GID=991 # getent group docker | cut -d: -f3
    restart: unless-stopped

#volumes:
#  arcane-data:
#    driver: local

```

**Comment by kmendell** [comment]
@driftywinds Can you try putting `user: root` to see if it then starts? Something with the rootless implementation must be off and i just want to confirm if that does indeed work.

```
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    user: root ##Add this line
    ports:
      - '3028:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./arcane-data:/app/data
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_GID=991 # getent group docker | cut -d: -f3
    restart: unless-stopped

#volumes:
#  arcane-data:
#    driver: local
```
