### ISSUE TITLE
🐞 Bug: login issue

### ISSUE THREAD

**Issue by schergr** [ofkm/arcane#118]
### Bug Description

unable to login with default uid and password. No errors .

The only thing difvferent about my config is I have the container public facing port as 3002. 

Compose is as follows:

```                                          
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - 3002:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./arcane-data:/app/data
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_GID=121 # getent group docker | cut -d: -f3
    restart: unless-stopped

# Optional: Define the volume if you want Docker to manage it
volumes:
   arcane-data:
```
```

Entrypoint: Running as root. Setting up user and permissions...
Entrypoint: Using PUID=1000, PGID=1000, DOCKER_GID=121
Entrypoint: Group with GID 1000 already exists: arcane
Entrypoint: Updating docker group from GID 998 to 121...
Entrypoint: User with UID 1000 already exists: arcane
Docker socket accessible at /var/run/docker.sock (GID: 121)
Entrypoint: Setting permissions on critical directories...
Starting Arcane as user arcane (1000:1000)...
Stacks directory initialized: /app/data/stacks
Auto-update is disabled in settings
Listening on http://0.0.0.0:3000
```

### Steps To Reproduce

docker compose up -d
uid: arcane
pwd: arcane-admin

### Expected Behavior

Successful login

### Actual Behavior

no errors....just no login

### Screenshots

![Image](https://github.com/user-attachments/assets/21f74f46-dd49-45c9-86dc-81f5d131884d)

### Arcane Version

0.4.1

### Operating System

Linux

### Browser

Chrome 135.0.7049.115

### Docker Version

26.1
