### ISSUE TITLE
🐞 Bug: 500 Error when starting stack

### ISSUE THREAD

**Issue by donslice** [ofkm/arcane#119]
### Bug Description

I am trying to migrate stack management over from Dockge. I am getting a 500 error when trying to start a stack.

I was able to start a different stack without specifying a network, so it seems to be related to my external network.

I moved Environment over to the stack since support for .env files isn't available yet.

```
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    #    ports:
    #      - 8090:8090
    volumes:
      - /opt/beszel/beszel_data:/beszel_data
    environment:
      - TZ=America/Detroit
      - PORT=45876
      - DOCKER_HOST=tcp://redacted
      - KEY=redacted
      - BESZEL_PASSWORD=redacted
    # env_file:
    #   - .env
    networks:
      - proxynet
    dns:
      - redacted
    labels:
      - homepage.group=Development
      - homepage.name=Beszel
      - homepage.icon=beszel.png
      - homepage.href=https://beszel.redacted
      - homepage.ping=http://beszel:8090
      - homepage.description=docker uptimes
      - homepage.widget.type=beszel
      - homepage.widget.url=http://beszel:8090
      - homepage.widget.username=redacted
      - homepage.widget.password=${BESZEL_PASSWORD}
      - homepage.widget.version=2
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.reece.casa`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls=true
      - traefik.http.routers.beszel.tls.certresolver=cloudflare
      - traefik.http.services.beszel.loadbalancer.server.port=8090

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Detroit
      - PORT=45876
      - DOCKER_HOST=tcp://redacted
      - KEY=redacted
      - BESZEL_PASSWORD=redacted
    # env_file:
    #   - .env
    volumes:
      - /mnt/data/.beszel:/extra-filesystems/sdc1:ro
      - /mnt/datastor/.beszel:/extra-filesystems/sda1:ro

networks:
  proxynet:
    external: true
```

### Steps To Reproduce

1. Create new Stack
2. Paste Stack yml
3. Save
4. Attempt Deploy

### Expected Behavior

Stack should start

### Actual Behavior

Instead, I get an error toast

![Image](https://github.com/user-attachments/assets/008e3d9e-2788-4176-bad9-2097109c2579)

and console error:

`error: "Failed to start stack: (HTTP code 404) no such container - network undefined not found "`

### Arcane Version

v0.4.1

### Operating System

Linux

### Browser

Firefox 137.0.2 (64-bit)

### Docker Version

26.1.4,

**Comment by kmendell** [comment]
i think your network block needs to look like this at least this is how i had success:

```
networks:
  proxynet:
    name: proxynet
    external: true
```
Can you try that and see if it works?
