### ISSUE TITLE
stacks Directory

### ISSUE THREAD

**Issue by cirrusflyer** [ofkm/arcane#126]
I noticed the documentation here:

https://arcane.ofkm.dev/docs/getting-started/configuration

States the stack locations are here:

stacksDirectory (string)

Defines the directory where Arcane stores and manages Docker Compose stack files.
Default: "/app/data/stacks"

But on my fresh install, I'm seeing them here:

./.dev-data/stacks

Is this incorrect or something else?

**Comment by kmendell** [comment]
Try to set the `APP_ENV=production` environment variable.

**Comment by peyloride** [comment]
I have this problem as well. And I believe because of this problem, I can't run stacks properly. My docker-compose.yml file for arcane:

```
alpine-docker:~/arcane# cat docker-compose.yml
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    user: root
    ports:
      - '3340:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    environment:
      - APP_ENV=production # Ensures the application uses production paths
      - DOCKER_GID=102 # Find using: getent group docker | cut -d: -f3
      - PUBLIC_SESSION_SECRET=your-secure-random-32-character-string-here # Generate using: openssl rand -base64 32
      - PUBLIC_ALLOW_INSECURE_COOKIES=true # Uncomment only for local HTTP testing without SSL/TLS
    restart: unless-stopped

volumes:
  arcane-data:
    driver: local
```

Notice there is `APP_ENV=production` present.
