### ISSUE TITLE
🐞 Bug: .env file not recognized

### ISSUE THREAD

**Issue by donslice** [ofkm/arcane#146]
### Bug Description

Created a stack using the `.env` feature. Starting stack results in 500 Error.

### Steps To Reproduce

1. Create Stack with compose.yaml
2. Ensure `.env_file` is set.
3. Create .env configuration
4. Save
5. Start

### Expected Behavior

Stack starts with no errors

### Actual Behavior

Instead, I get a 500 Error.

Browser Dev console shows: `{ success: false, error: "Failed to start stack: ENOENT: no such file or directory, open '.env'" }`

### Screenshots

![Image](https://github.com/user-attachments/assets/cde0c17e-4783-4ebe-8a36-d6b07a7d323c)

![Image](https://github.com/user-attachments/assets/9a60597a-4b81-48f3-af71-dca601257750)

### Arcane Version

v.0.7.0

### Operating System

Linux

### Browser

Firefox 138

### Docker Version

26.1.4

### Additional Context

Arcane Compose

```
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    hostname: arcane
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/arcane:/app/data
    networks:
      - proxynet
    environment:
      - PUID=1000
      - PGID=1000
      - APP_ENV=production
      - DOCKER_GID=998
      - PUBLIC_SESSION_SECRET=
      - PUBLIC_ALLOW_INSECURE_COOKIES=false
    restart: unless-stopped

networks:
  proxynet:
    name: proxynet
    external: true

```
