### ISSUE TITLE
Can't assign network

### ISSUE THREAD

**Issue by koinupapi** [ofkm/arcane#206]
When I create a stack and use the "networks" yaml key to assign a network, it will not do it.

I use:
```
networks:
    default:
        external: true
        name: rmg
```
this works in regular yaml text editors, and in dockge, but when I try using it in Arcane, it just adds the container to the bridge network.
