### ISSUE TITLE
🐞 Bug: Redploying duplicates network and then stops

### ISSUE THREAD

**Issue by EmberLightVFX** [ofkm/arcane#269]
### Bug Description

If you create a stack with network creation in the compose file and then you redeploy, Arcane will re-create the network but then stop as there now is two networks with the same name.

### Steps To Reproduce

1. Create a stack like this:

```yaml
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_service
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - nginx_data:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - testnetwork
      
networks:
  testnetwork:
    name: testnetwork

volumes:
  nginx_data:
    driver: local
```
2. Depoly
3. When deployed, redeoply it
4. You'll now get an error that there is two testnetwork-networks and the stack won't get depolyed.

### Expected Behavior

Arcane should see that the network already exist and use it instead of creating a duplicate.

### Actual Behavior

Arcane duplicates the network.

### Arcane Version

v0.13.0

### Operating System

Linux

### Browser

Firefox

### Docker Version

24.0.2
