### ISSUE TITLE
🐞 Bug: 0.15.0 does not mount volumes

### ISSUE THREAD

**Issue by EmberLightVFX** [ofkm/arcane#278]
### Bug Description

When you bind a volume to a physical location on your server, the location isn't being bind when launching the stack.

I tried 0.14.0 and it does not have this problem so it's something that arrived with 0.15.0

### Steps To Reproduce

Create a new stack like this:

```yaml
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_service
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - <<physical location>>:/test
    restart: unless-stopped
```

Replace <<physical location>> with a location on your server.
After deploying the stack, go into the container and go down to `Storage & Mounts`, it's empty.
If you place a file in your physical location and then enter the container and go to /test, you won't see any files there and most likeley you won't even have a folder called /test in root.

### Expected Behavior

The volume should bind like it did in 0.14.0

### Actual Behavior

The volume does not bind at all.

### Arcane Version

0.15.0

### Operating System

Linux

### Browser

Firefox

### Docker Version

24.0.6
