### ISSUE TITLE
🐞 Bug: Arcane ignoring bind mounts in compose projects

### ISSUE THREAD

**Issue by WarlockSyno** [ofkm/arcane#283]
### Bug Description

Copied all of my compose documents into Arcane and found an issue where if I redeploy the stack through Arcane, the bind mounts don't get attached.

### Steps To Reproduce

1. Create a new Compose Project
2. Add compose YAML with a bind mount
Ex:
```yaml
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - /opt/flame/:/app/data/
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration feature
    ports:
      - 5005:5005
    environment:
      - PASSWORD=password
    restart: unless-stopped
```

3. Deploy the compose
4. Check bind mounts on the container services

### Expected Behavior

Expected the container to have bind mount to the host as listed in the Compose file

### Actual Behavior

No bind mounts added

Running Docker Compose outside of Arcane does create the bind mount though

### Arcane Version

v0.15.0

### Operating System

Linux

### Browser

Firefox 139.0.1

### Docker Version

26.1.4

### Additional Context

Tried changing the UID and GID within the compose file for Arcane, no changes made a difference
