### ISSUE TITLE
🐞 Bug: Cannot run Arcane (gid in use)

### ISSUE THREAD

**Issue by dippin-with-alex** [ofkm/arcane#304]
### Bug Description

Hello guys! Im trying to try out arcane! looks amazing but im having such a hard time to put it to work :/ if anyone could point me to the right direction would be awesome!

docker compose
```Dockerfile
services:
  arcane:
    image: ghcr.io/ofkm/arcane:development
    container_name: arcane
    restart: unless-stopped
    user: root
    ports:
      - '3000:3000'
    environment:
      - APP_ENV=production
      - PUBLIC_SESSION_SECRET=ZVmFknfZ5rJ1TyQLesRTWwM8iAuOfyt9+6DzqE2w2Vg=
      - PUID=0
      - PGID=0
      - DOCKER_GID=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/arcane:/app/data
```

logs
```bash
Entrypoint: Setting up user and permissions...
Entrypoint: Using PUID=0, PGID=0, DOCKER_GID=0
Entrypoint: Group with GID 0 already exists: root
Entrypoint: Creating docker group with GID 0...
addgroup: gid '0' in use
```

### Steps To Reproduce

using the compose it will infinity crash and reload with the same log

### Expected Behavior

run the service

### Actual Behavior

crash

### Arcane Version

latest

### Operating System

DSM 7.2.2-72806 Update 3

### Browser

chrome

### Docker Version

Docker version 24.0.2, build 610b8d0

**Comment by MohandL3G** [comment]
Same, I'm using Docker Desktop for Windows, and I thought the problem was from it, hopefully they fix it

**Comment by kmendell** [comment]
What happens if you use user: root? I dont think it should matter technially..

**Comment by dippin-with-alex** [comment]
> What happens if you use user: root? I dont think it should matter technially..

its what I have I also tried without it and it was the same

**Comment by vladaurosh** [comment]
Why are you setting DOCKER_GID to 0? 0 is root user's group. 
Purpose of docker group is to allow non-privileged users to run docker commands. 
Setting it to 0 doesn't make any sense.

**Comment by fuxing-at** [comment]
Same here. I tried my default admin group id, 998 and 0. But without any success.

**Comment by kmendell** [comment]
I'm not sure why this is happening, i can't replicate it, does it happen on multiple servers if you can try that?

**Comment by dartmoordunbar** [comment]
I had this issue when I installed docker onto Ubuntu server and then followed the rootless user steps. When I removed it and just added my user to the docker group it worked for me.

**Comment by whiteki08** [comment]
I'm using OrbStack on macOS and I encountered the same problem.
```
services:
  arcane:
    image: ghcr.nju.edu.cn/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '23456:3000'
    volumes:
      - /Users/yifans/.orbstack/run/docker.sock:/var/run/docker.sock
      - /Users/yifans/arcane/data:/app/data
    environment:
      - APP_ENV=production # Required
      - PUBLIC_SESSION_SECRET=******* # Generate: openssl rand -base64 32
      # Optional: Match your host user for permissions
      - PUID=501
      - PGID=20
      # Optional: Set if Docker access fails
      # - DOCKER_GID=20
      # Optional: For local HTTP testing only
      # - PUBLIC_ALLOW_INSECURE_COOKIES=true
    restart: unless-stopped

volumes:
  arcane-data:
    driver: local
```
By the way, I can use DPanel normally. Very confusing.
