### ISSUE TITLE
🐞 Bug:  Cannot run Arcane in DSM918+ (gid in use)

### ISSUE THREAD

**Issue by wesmile8** [ofkm/arcane#320]
### Bug description
i used docker-compose.yml ,but the logs show :
```
root@yzy_nas_1820:/volume1/docker/Arcane# docker logs -f arcane 
Entrypoint: Setting up user and permissions...
Entrypoint: Using PUID=2000, PGID=2000, DOCKER_GID=998
Entrypoint: Creating group arcane with GID 2000...
Entrypoint: Creating docker group with GID 998...
Entrypoint: Creating user arcane with UID 2000 and GID 2000...
Entrypoint: Adding arcane to the docker group...
addgroup: gid '0' in use
```
my docker-compose.yml:
```
version: '3.9'
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - "13220:3000"
    volumes:
      - /volume1/docker/Arcane/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=2000
      - PGID=2000
      #- DOCKER_GID=998
      - APP_ENV=production
      - PUBLIC_SESSION_SECRET=MY_SESSION_SECRET
    restart: unless-stopped
    network_mode: "bridge"
```
i try uid/gid=0 ,but it's not work, also i set DOCKER_GID=998, logs show the same question

### Steps To Reproduce

deployed Arcane v0.15.1 in DSM918+ with Docker (version 20.10.3)

### Expected Behavior

plz fix it

### Actual Behavior

addgroup: gid '0' in use

### Screenshots

![Image](https://github.com/user-attachments/assets/3881f187-07cf-48d0-a256-217489ad1118)

### Arcane Version

v0.15.1

### Operating System

Linux

### Browser

chrome

### Docker Version

Docker version 20.10.3, build b35e731
